services:
  apollo-router:
    image: ghcr.io/apollographql/router:v2.5.0
    ports:
      - "4000:4000"         # Router GraphQL endpoint
      - "8088:8088"         # Health check endpoint (if enabled in config)
    environment:
      APOLLO_GRAPH_REF: "${APOLLO_GRAPH_REF}"
      APOLLO_KEY: "${APOLLO_KEY}"
    volumes:
      - ./router.yaml:/dist/config.yaml
      - ./supergraph.graphql:/dist/supergraph.graphql
    command: >
      --config /dist/config.yaml
