---
name: Test Kubernetes Deployment

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-k8s-deployment:
    name: Test Kubernetes Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test Docker image
        run: |
          cd subgraphs
          docker build -t subgraphs:test .

          # Verify the image was created
          if ! docker images | grep -q "subgraphs.*test"; then
            echo "❌ Docker build failed for subgraphs"
            exit 1
          fi

          echo "✅ Subgraphs Docker build successful"

